amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99
    odom_model_type: "diff-corrected"
    update_min_d: 0.2
    update_min_a: 0.5
    resample_interval: 1
    transform_tolerance: 0.1
    laser_model_type: "likelihood_field"
    laser_z_hit: 0.95
    laser_sigma_hit: 0.2
    laser_z_rand: 0.05
    laser_likelihood_max_dist: 2.0
