# Default initial positions for manipulator_mobile_bringup's ros2_control fake system

initial_positions:
  gripper_base_joint: 0
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  left_gear_joint: 0