controller_joint_names: ['', 'joint_1', 'joint_2', 'joint_3', 'joint_4', 'gripper_base_joint', 'left_gear_joint', 'left_finger_joint', 'right_gear_joint', 'right_finger_joint', 'left_joint', 'right_joint', ]
